ラーニングページ作成
Mayumi-Nakabayashi/withTone pull request #126
Opened 2023-10-25 07:59 UTC by sodateya

## やったこと
- ラーニングページ作成
- フィードバックのボトムシート作成

## やってないこと
- 背景の動画は設置していません

## サンプル動画
https://github.com/Mayumi-Nakabayashi/withTone/assets/79615420/801ab072-f7cd-4052-8c97-4634d86b2459

2023-10-25 09:40 UTC, ken-ty requested changes
UI 作成ありがとうございます！いくつかコメントしました。

> 背景の動画は設置していません

了解です！一旦このままやらなくてOKです。定期的な issue 棚卸しで必要なら対応issue作成などすれば良いかと。

> @Mayumi-Nakabayashi
> https://github.com/Mayumi-Nakabayashi/withTone/issues/75
> #75の２枚目３枚目への画面遷移などがわからなかったので後日確認させてください。

こちらは別途ご確認お願いします 🙏

2023-10-25 09:40 UTC, ken-ty commented on lib/views/components/favorite_button.dart
> +class FavoriteBotton extends StatefulWidget {
typo:
Botton → Button

2023-10-25 09:40 UTC, ken-ty commented on lib/views/pages/learning_community_home/widget/feedback_bottom_sheet.dart
> +    TextEditingController c = TextEditingController();
build 内部に controller を配置すると、リビルドで初期化されてしまいますが想定通りでしょうか？

https://qiita.com/kurararara/items/b59ff3f8d6a2ce416220
上記のように build 外に配置するのが良さそうです。

2023-10-25 09:40 UTC, ken-ty commented on lib/views/pages/learning_community_home/widget/feedback_button.dart
> +///とりあえずフィードバックコメントのみ
👍

2023-10-25 11:04 UTC, sodateya commented on lib/views/pages/learning_community_home/widget/feedback_bottom_sheet.dart
> +    TextEditingController c = TextEditingController();
すいませんとりあえず適当に配置してしまっていました！

2023-10-25 11:07 UTC, sodateya commented on lib/views/components/favorite_button.dart
> +class FavoriteBotton extends StatefulWidget {
修正しました！[dfb46f8](https://github.com/Mayumi-Nakabayashi/withTone/pull/126/commits/dfb46f87c6304ecb0352595f6d7d3550e446b2cf)

2023-10-25 11:08 UTC, sodateya commented on lib/views/pages/learning_community_home/widget/feedback_bottom_sheet.dart
> +    TextEditingController c = TextEditingController();
修正しました！[dc68d45](https://github.com/Mayumi-Nakabayashi/withTone/pull/126/commits/dc68d45215200ed995f8dd8ed741977218d30c5d)

今後hooksとか使う予定ありますかね？

2023-10-30 01:52 UTC, ken-ty commented on lib/views/pages/learning_community_home/widget/feedback_bottom_sheet.dart
> +    TextEditingController c = TextEditingController();
hooks は便利ですが学習コストかかっちゃうので、現状難しそう。
正式リリースできたら保守・改善メンバーがリファクタとしてやるのは良さそう。

一旦 issue にしておきますね。

2023-10-30 01:54 UTC, ken-ty commented on lib/views/pages/learning_community_home/widget/feedback_bottom_sheet.dart
> +    TextEditingController c = TextEditingController();
#128

2023-10-30 01:55 UTC, ken-ty approved these changes
LGTM!!

2023-10-30 01:56 UTC, ken-ty commented
> @Mayumi-Nakabayashi
> https://github.com/Mayumi-Nakabayashi/withTone/issues/75
> #75の２枚目３枚目への画面遷移などがわからなかったので後日確認させてください。

こちら済んだらマージしていただけると！

2023-10-30 02:14 UTC, merged