スプラッシュ画面にロゴのアニメーションを追加 #38
Mayumi-Nakabayashi/withTone pull request #133
Opened 2023-11-01 18:08 UTC by Mayumi-Nakabayashi

## 該当する issue 
#38  

## やったこと

Lottieを使ってスプラッシュ画面にロゴのアニメーションを作成した。

2023-11-03 08:53 UTC, ken-ty commented
suggestion:
繰り返し再生されるのちょっとダサいので、１回再生したら止めたいです。
https://github.com/Mayumi-Nakabayashi/withTone/assets/38717219/36fab85c-8248-4d8a-9bde-8e05e2a3e3b9

2023-11-03 09:09 UTC, ken-ty commented
nits:

commit message が feat: と summary の間に改行が含まれてしまってます。修正は必要ないです、気をつけていただければ！

![スクリーンショット 2023-11-03 18 08 41](https://github.com/Mayumi-Nakabayashi/withTone/assets/38717219/1a37b8de-d404-4e8d-9806-5d2153c6e9f2)

2023-11-03 09:10 UTC, ken-ty requested changes
コメントしました。また、コンフリクトが発生しているので最新の develop を取り込んで解決をお願いします！

pubspec.lock
pubspec.yaml

2023-11-03 09:10 UTC, ken-ty commented on lib/views/pages/intro/constantly_moving_lottie.dart
> +  const ConstantlyMoving({super.key, required this.asset});
size は 外から指定できた方が調整しやすそう。

```suggestion
const ConstantlyMoving({super.key, this.size = 380});
final int size;
...
return SizedBox(width: size, height: size,...)
...
```

2023-11-03 09:10 UTC, ken-ty commented on lib/views/pages/intro/constantly_moving_lottie.dart
> +              return const Center(child: CircularProgressIndicator());
これだと、読み込まれるまで小さいローディングが出るので、読み込み完了時に画面にガタつきが発生します。
SizedBox は feaatureBuilder の外に出してあげましょう。あとColumnは要らなそう。

```suggestion
return SizedBox(
  width: size,
  height: size,
  child: FutureBUilder<LottieComposition>(
    ... ( SizedBox は削除 )
  ),
);
```

2023-11-03 09:10 UTC, ken-ty commented on lib/views/pages/intro/intro_page.dart
> +
余計な余白がcommitに含まれちゃってます

2023-11-07 15:36 UTC, Mayumi-Nakabayashi commented
@ken-ty 
コンフリクト解消しました！

2023-11-09 12:07 UTC, ken-ty approved these changes

2023-11-09 12:08 UTC, merged

2023-11-09 12:14 UTC, ken-ty commented on lib/views/pages/intro/constantly_moving_lottie.dart
> +...
すいません、マージして気づいたのですがここら辺 おかしくなっちゃってます、
自分修正しますね！

2023-11-09 12:14 UTC, ken-ty commented on lib/views/pages/intro/constantly_moving_lottie.dart
> +    ... ( SizedBox は削除 )
ここも